// Package transpile lowers a pyc.Code object tree into a single Go
// source file that, when compiled, reproduces the program's
// observable behaviour. The v0.1 mapping is a direct one-to-one of
// CPython 3.14 bytecode into stack-machine Go; optimisation is a
// separate pass that does not exist yet.
package transpile

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/tamnd/gopygo/pyc"
)

// Compile takes a root code object, the desired package name, and a
// function prefix, and returns the Go source as bytes.
//
// The root is expected to be the module-level code object produced
// by `py_compile`. Transpile emits:
//   - one Go function per Code object reachable from root via Consts
//   - a `main()` that invokes the module function
//   - a top-level globals map shared by the module function and any
//     nested function that uses LOAD_NAME/STORE_NAME
func Compile(root *pyc.Code, pkgName string) ([]byte, error) {
	g := &gen{
		pkg:    pkgName,
		funcOf: make(map[*pyc.Code]string),
	}
	g.assignName(root, "py_module")
	g.enqueue(root)
	for len(g.queue) > 0 {
		c := g.queue[0]
		g.queue = g.queue[1:]
		if err := g.emitFunc(c); err != nil {
			return nil, fmt.Errorf("%s: %w", c.QualName, err)
		}
	}
	return g.assemble(), nil
}

type gen struct {
	pkg     string
	header  bytes.Buffer
	body    bytes.Buffer
	queue   []*pyc.Code
	funcOf  map[*pyc.Code]string
	counter int
}

func (g *gen) assignName(c *pyc.Code, want string) string {
	if n, ok := g.funcOf[c]; ok {
		return n
	}
	n := want
	if n == "" {
		n = "py_" + sanitise(c.QualName)
	}
	// Disambiguate when the same qualname recurs (e.g. <listcomp>).
	g.counter++
	n = fmt.Sprintf("%s__%d", n, g.counter)
	g.funcOf[c] = n
	return n
}

func (g *gen) enqueue(c *pyc.Code) {
	g.queue = append(g.queue, c)
}

func sanitise(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9'):
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	if b.Len() == 0 {
		return "py"
	}
	return b.String()
}

func (g *gen) assemble() []byte {
	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by gopygo. DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "package %s\n\n", g.pkg)
	fmt.Fprintf(&out, "import (\n")
	fmt.Fprintf(&out, "\t\"fmt\"\n")
	fmt.Fprintf(&out, "\t\"os\"\n")
	fmt.Fprintf(&out, "\n")
	fmt.Fprintf(&out, "\trt \"github.com/tamnd/gopygo/runtime\"\n")
	fmt.Fprintf(&out, ")\n\n")
	fmt.Fprintf(&out, "var globals = map[string]rt.Value{}\n\n")
	fmt.Fprintf(&out, "func loadName(name string) rt.Value {\n")
	fmt.Fprintf(&out, "\tif v, ok := globals[name]; ok { return v }\n")
	fmt.Fprintf(&out, "\tif v, ok := rt.Builtins[name]; ok { return v }\n")
	fmt.Fprintf(&out, "\tpanic(fmt.Sprintf(\"NameError: name %%q is not defined\", name))\n")
	fmt.Fprintf(&out, "}\n\n")
	fmt.Fprintf(&out, "func main() {\n")
	fmt.Fprintf(&out, "\tif _, err := %s(nil); err != nil {\n", g.funcOf[g.rootCode()])
	fmt.Fprintf(&out, "\t\tfmt.Fprintln(os.Stderr, err); os.Exit(1)\n")
	fmt.Fprintf(&out, "\t}\n")
	fmt.Fprintf(&out, "}\n\n")
	out.Write(g.body.Bytes())
	return out.Bytes()
}

func (g *gen) rootCode() *pyc.Code {
	// The root was the first code enqueued; its name starts with "py_module".
	for c, n := range g.funcOf {
		if strings.HasPrefix(n, "py_module__") {
			return c
		}
	}
	return nil
}
