//go:build ignore

// Code generated by gopygo. DO NOT EDIT.

package main

import (
	"fmt"
	"math"
	"strconv"
	"strings"
)

func main() {
	var a int64 = 7
	var b int64 = 3
	pyPrintln((a + b))
	pyPrintln((a - b))
	pyPrintln((a * b))
	pyPrintln((float64(a) / float64(b)))
	pyPrintln((a / b))
	pyPrintln((a % b))
	pyPrintln(-a)
	pyPrintln(int64(math.Pow(float64(2), float64(10))))
}

func pyRepr(v any) string {
	switch x := v.(type) {
	case bool:
		if x {
			return "True"
		}
		return "False"
	case float64:
		if x == float64(int64(x)) {
			return strconv.FormatFloat(x, 'f', 1, 64)
		}
		return strconv.FormatFloat(x, 'g', -1, 64)
	case string:
		return x
	}
	return fmt.Sprint(v)
}

func pyPrintln(args ...any) {
	parts := make([]string, len(args))
	for i, a := range args {
		parts[i] = pyRepr(a)
	}
	fmt.Println(strings.Join(parts, " "))
}
