//go:build ignore

// Code generated by gopygo. DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	rt "github.com/tamnd/gopygo/runtime"
)

var globals = map[string]rt.Value{}

func loadName(name string) rt.Value {
	if v, ok := globals[name]; ok {
		return v
	}
	if v, ok := rt.Builtins[name]; ok {
		return v
	}
	panic(fmt.Sprintf("NameError: name %q is not defined", name))
}

func main() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, r)
			os.Exit(1)
		}
	}()
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Compare(0, rt.NewIntInt(1), rt.NewIntInt(2)))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Compare(0, rt.NewIntInt(2), rt.NewIntInt(1)))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Boxed(rt.Equal(rt.NewIntInt(1), rt.NewIntInt(1)))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Boxed(!rt.Equal(rt.NewIntInt(1), rt.NewIntInt(2)))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Compare(1, rt.NewIntInt(1), rt.NewIntInt(1)))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Compare(5, rt.NewIntInt(1), rt.NewIntInt(2)))))
	_ = rt.Must(rt.Call(loadName("print"), func() rt.Value {
		_cl1 := rt.NewIntInt(1)
		_cr2 := rt.NewIntInt(2)
		if !rt.Truthy(rt.Must(rt.Compare(0, _cl1, _cr2))) {
			return rt.False
		}
		_cr3 := rt.NewIntInt(3)
		if !rt.Truthy(rt.Must(rt.Compare(0, _cr2, _cr3))) {
			return rt.False
		}
		return rt.True
	}()))
	_ = rt.Must(rt.Call(loadName("print"), func() rt.Value {
		_cl4 := rt.NewIntInt(1)
		_cr5 := rt.NewIntInt(2)
		if !rt.Truthy(rt.Must(rt.Compare(0, _cl4, _cr5))) {
			return rt.False
		}
		_cr6 := rt.NewIntInt(0)
		if !rt.Truthy(rt.Must(rt.Compare(0, _cr5, _cr6))) {
			return rt.False
		}
		return rt.True
	}()))
	_ = rt.Must(rt.Call(loadName("print"), func() rt.Value {
		if !rt.Truthy(rt.True) {
			return rt.True
		}
		return rt.False
	}()))
	_ = rt.Must(rt.Call(loadName("print"), func() rt.Value {
		if rt.Truthy(rt.True) {
			return rt.True
		}
		return rt.False
	}()))
	_ = rt.Must(rt.Call(loadName("print"), rt.Not(rt.True)))
	_ = rt.Must(rt.Call(loadName("print"), rt.Not(rt.NewIntInt(0))))
}
