//go:build ignore

// Code generated by gopygo. DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	rt "github.com/tamnd/gopygo/runtime"
)

var globals = map[string]rt.Value{}

func loadName(name string) rt.Value {
	if v, ok := globals[name]; ok {
		return v
	}
	if v, ok := rt.Builtins[name]; ok {
		return v
	}
	panic(fmt.Sprintf("NameError: name %q is not defined", name))
}

func main() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, r)
			os.Exit(1)
		}
	}()
	var i rt.Value
	var j rt.Value
	var k rt.Value
	var total rt.Value
	var x rt.Value
	x = rt.NewIntInt(5)
	globals["x"] = x
	if rt.Truthy(rt.Must(rt.Compare(4, x, rt.NewIntInt(10)))) {
		_ = rt.Must(rt.Call(loadName("print"), rt.NewStr("big")))
	} else if rt.Truthy(rt.Must(rt.Compare(4, x, rt.NewIntInt(0)))) {
		_ = rt.Must(rt.Call(loadName("print"), rt.NewStr("small positive")))
	} else {
		_ = rt.Must(rt.Call(loadName("print"), rt.NewStr("non-positive")))
	}
	i = rt.NewIntInt(0)
	globals["i"] = i
	for rt.Truthy(rt.Must(rt.Compare(0, i, rt.NewIntInt(3)))) {
		_ = rt.Must(rt.Call(loadName("print"), rt.NewStr("while"), i))
		i = rt.Must(rt.Add(i, rt.NewIntInt(1)))
		globals["i"] = i
	}
	{
		_it1 := rt.MustIter(rt.GetIter(rt.Must(rt.Call(loadName("range"), rt.NewIntInt(4)))))
		for {
			_v, _ok := _it1.Next()
			if !_ok {
				break
			}
			j = _v
			globals["j"] = j
			if rt.Truthy(rt.Boxed(rt.Equal(j, rt.NewIntInt(2)))) {
				continue
			}
			if rt.Truthy(rt.Boxed(rt.Equal(j, rt.NewIntInt(3)))) {
				break
			}
			_ = rt.Must(rt.Call(loadName("print"), rt.NewStr("for"), j))
		}
	}
	total = rt.NewIntInt(0)
	globals["total"] = total
	{
		_it2 := rt.MustIter(rt.GetIter(rt.Must(rt.Call(loadName("range"), rt.NewIntInt(1), rt.NewIntInt(6)))))
		for {
			_v, _ok := _it2.Next()
			if !_ok {
				break
			}
			k = _v
			globals["k"] = k
			total = rt.Must(rt.Add(total, k))
			globals["total"] = total
		}
	}
	_ = rt.Must(rt.Call(loadName("print"), rt.NewStr("total"), total))
}
