//go:build ignore

// Code generated by gopygo. DO NOT EDIT.

package main

import (
	"fmt"
	"strconv"
	"strings"
)

func main() {
	for i := int64(0); i < 5; i++ {
		pyPrintln(i)
	}
	for j := int64(2); j < 6; j++ {
		pyPrintln(j)
	}
	for k := int64(10); k > 0; k += -2 {
		pyPrintln(k)
	}
}

func pyRepr(v any) string {
	switch x := v.(type) {
	case bool:
		if x {
			return "True"
		}
		return "False"
	case float64:
		if x == float64(int64(x)) {
			return strconv.FormatFloat(x, 'f', 1, 64)
		}
		return strconv.FormatFloat(x, 'g', -1, 64)
	case string:
		return x
	}
	return fmt.Sprint(v)
}

func pyPrintln(args ...any) {
	parts := make([]string, len(args))
	for i, a := range args {
		parts[i] = pyRepr(a)
	}
	fmt.Println(strings.Join(parts, " "))
}
