//go:build ignore

// Code generated by gopygo. DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	rt "github.com/tamnd/gopygo/runtime"
)

var globals = map[string]rt.Value{}

func loadName(name string) rt.Value {
	if v, ok := globals[name]; ok {
		return v
	}
	if v, ok := rt.Builtins[name]; ok {
		return v
	}
	panic(fmt.Sprintf("NameError: name %q is not defined", name))
}

var _fn_minmax = &rt.Func{Name: "minmax", Arity: 1, Impl: _impl_minmax}

func _impl_minmax(_args []rt.Value) (rt.Value, error) {
	if len(_args) != 1 {
		return nil, rt.TypeError("minmax() takes 1 positional arguments but %d were given", len(_args))
	}
	xs := _args[0]
	var hi rt.Value
	var lo rt.Value
	var v rt.Value
	_ = _args
	lo = rt.Must(rt.GetItem(xs, rt.NewIntInt(0)))
	hi = rt.Must(rt.GetItem(xs, rt.NewIntInt(0)))
	{
		_it1 := rt.MustIter(rt.GetIter(xs))
		for {
			_v, _ok := _it1.Next()
			if !_ok {
				break
			}
			v = _v
			if rt.Truthy(rt.Must(rt.Compare(0, v, lo))) {
				lo = v
			}
			if rt.Truthy(rt.Must(rt.Compare(4, v, hi))) {
				hi = v
			}
		}
	}
	return rt.NewTuple(lo, hi), nil
	return rt.None, nil
}

func main() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, r)
			os.Exit(1)
		}
	}()
	var a rt.Value
	var b rt.Value
	var hi rt.Value
	var lo rt.Value
	var minmax rt.Value
	var p rt.Value
	var x rt.Value
	var y rt.Value
	var z rt.Value
	minmax = _fn_minmax
	globals["minmax"] = minmax
	p = rt.NewTuple(rt.NewIntInt(1), rt.NewIntInt(2))
	globals["p"] = p
	_ = rt.Must(rt.Call(loadName("print"), p))
	_t2 := rt.MustIter(rt.GetIter(p))
	var _tv3 []rt.Value
	for {
		v, ok := _t2.Next()
		if !ok {
			break
		}
		_tv3 = append(_tv3, v)
	}
	if len(_tv3) != 2 {
		panic(rt.TypeError("unpack: expected 2, got %d", len(_tv3)))
	}
	a = _tv3[0]
	globals["a"] = a
	b = _tv3[1]
	globals["b"] = b
	_ = rt.Must(rt.Call(loadName("print"), a, b))
	_t4 := rt.MustIter(rt.GetIter(rt.NewTuple(b, a)))
	var _tv5 []rt.Value
	for {
		v, ok := _t4.Next()
		if !ok {
			break
		}
		_tv5 = append(_tv5, v)
	}
	if len(_tv5) != 2 {
		panic(rt.TypeError("unpack: expected 2, got %d", len(_tv5)))
	}
	a = _tv5[0]
	globals["a"] = a
	b = _tv5[1]
	globals["b"] = b
	_ = rt.Must(rt.Call(loadName("print"), a, b))
	_t6 := rt.MustIter(rt.GetIter(rt.NewTuple(rt.NewIntInt(10), rt.NewIntInt(20), rt.NewIntInt(30))))
	var _tv7 []rt.Value
	for {
		v, ok := _t6.Next()
		if !ok {
			break
		}
		_tv7 = append(_tv7, v)
	}
	if len(_tv7) != 3 {
		panic(rt.TypeError("unpack: expected 3, got %d", len(_tv7)))
	}
	x = _tv7[0]
	globals["x"] = x
	y = _tv7[1]
	globals["y"] = y
	z = _tv7[2]
	globals["z"] = z
	_ = rt.Must(rt.Call(loadName("print"), x, y, z))
	_t8 := rt.MustIter(rt.GetIter(rt.Must(rt.Call(minmax, rt.NewTuple(rt.NewIntInt(3), rt.NewIntInt(1), rt.NewIntInt(4), rt.NewIntInt(1), rt.NewIntInt(5), rt.NewIntInt(9), rt.NewIntInt(2), rt.NewIntInt(6))))))
	var _tv9 []rt.Value
	for {
		v, ok := _t8.Next()
		if !ok {
			break
		}
		_tv9 = append(_tv9, v)
	}
	if len(_tv9) != 2 {
		panic(rt.TypeError("unpack: expected 2, got %d", len(_tv9)))
	}
	lo = _tv9[0]
	globals["lo"] = lo
	hi = _tv9[1]
	globals["hi"] = hi
	_ = rt.Must(rt.Call(loadName("print"), lo, hi))
}
