//go:build ignore

// Code generated by gopygo. DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	rt "github.com/tamnd/gopygo/runtime"
)

var globals = map[string]rt.Value{}

func loadName(name string) rt.Value {
	if v, ok := globals[name]; ok {
		return v
	}
	if v, ok := rt.Builtins[name]; ok {
		return v
	}
	panic(fmt.Sprintf("NameError: name %q is not defined", name))
}

var _fn_minmax = &rt.Func{Name: "minmax", Arity: 1, Impl: _impl_minmax}

func _impl_minmax(_args []rt.Value) (rt.Value, error) {
	if len(_args) != 1 {
		return nil, rt.TypeError("minmax() takes 1 positional arguments but %d were given", len(_args))
	}
	xs := _args[0]
	var hi rt.Value
	var lo rt.Value
	var v rt.Value
	_ = _args
	lo = rt.Must(rt.GetItem(xs, rt.NewIntInt(0)))
	hi = rt.Must(rt.GetItem(xs, rt.NewIntInt(0)))
	{
		_it1 := rt.MustIter(rt.GetIter(xs))
		for {
			_v, _ok := _it1.Next()
			if !_ok {
				break
			}
			v = _v
			if rt.Truthy(rt.Must(rt.Compare(0, v, lo))) {
				lo = v
			}
			if rt.Truthy(rt.Must(rt.Compare(4, v, hi))) {
				hi = v
			}
		}
	}
	return rt.NewTuple(lo, hi), nil
	return rt.None, nil
}

func main() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, r)
			os.Exit(1)
		}
	}()
	var a rt.Value
	var b rt.Value
	var hi rt.Value
	var lo rt.Value
	var minmax rt.Value
	var p rt.Value
	var x rt.Value
	var y rt.Value
	var z rt.Value
	minmax = _fn_minmax
	globals["minmax"] = minmax
	p = rt.NewTuple(rt.NewIntInt(1), rt.NewIntInt(2))
	globals["p"] = p
	_ = rt.Must(rt.Call(loadName("print"), p))
	_tv2 := func() []rt.Value {
		_it := rt.MustIter(rt.GetIter(p))
		var xs []rt.Value
		for {
			v, ok := _it.Next()
			if !ok {
				break
			}
			xs = append(xs, v)
		}
		if len(xs) != 2 {
			panic(rt.TypeError("unpack: expected 2, got %d", len(xs)))
		}
		return xs
	}()
	a = _tv2[0]
	globals["a"] = a
	b = _tv2[1]
	globals["b"] = b
	_ = rt.Must(rt.Call(loadName("print"), a, b))
	_tv3 := func() []rt.Value {
		_it := rt.MustIter(rt.GetIter(rt.NewTuple(b, a)))
		var xs []rt.Value
		for {
			v, ok := _it.Next()
			if !ok {
				break
			}
			xs = append(xs, v)
		}
		if len(xs) != 2 {
			panic(rt.TypeError("unpack: expected 2, got %d", len(xs)))
		}
		return xs
	}()
	a = _tv3[0]
	globals["a"] = a
	b = _tv3[1]
	globals["b"] = b
	_ = rt.Must(rt.Call(loadName("print"), a, b))
	_tv4 := func() []rt.Value {
		_it := rt.MustIter(rt.GetIter(rt.NewTuple(rt.NewIntInt(10), rt.NewIntInt(20), rt.NewIntInt(30))))
		var xs []rt.Value
		for {
			v, ok := _it.Next()
			if !ok {
				break
			}
			xs = append(xs, v)
		}
		if len(xs) != 3 {
			panic(rt.TypeError("unpack: expected 3, got %d", len(xs)))
		}
		return xs
	}()
	x = _tv4[0]
	globals["x"] = x
	y = _tv4[1]
	globals["y"] = y
	z = _tv4[2]
	globals["z"] = z
	_ = rt.Must(rt.Call(loadName("print"), x, y, z))
	_tv5 := func() []rt.Value {
		_it := rt.MustIter(rt.GetIter(rt.Must(rt.Call(minmax, rt.NewTuple(rt.NewIntInt(3), rt.NewIntInt(1), rt.NewIntInt(4), rt.NewIntInt(1), rt.NewIntInt(5), rt.NewIntInt(9), rt.NewIntInt(2), rt.NewIntInt(6))))))
		var xs []rt.Value
		for {
			v, ok := _it.Next()
			if !ok {
				break
			}
			xs = append(xs, v)
		}
		if len(xs) != 2 {
			panic(rt.TypeError("unpack: expected 2, got %d", len(xs)))
		}
		return xs
	}()
	lo = _tv5[0]
	globals["lo"] = lo
	hi = _tv5[1]
	globals["hi"] = hi
	_ = rt.Must(rt.Call(loadName("print"), lo, hi))
}
