//go:build ignore

// Code generated by gopygo. DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	rt "github.com/tamnd/gopygo/runtime"
)

var globals = map[string]rt.Value{}

func loadName(name string) rt.Value {
	if v, ok := globals[name]; ok {
		return v
	}
	if v, ok := rt.Builtins[name]; ok {
		return v
	}
	panic(fmt.Sprintf("NameError: name %q is not defined", name))
}

func main() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, r)
			os.Exit(1)
		}
	}()
	var total rt.Value
	var v rt.Value
	var xs rt.Value
	xs = &rt.List{V: []rt.Value{rt.NewIntInt(1), rt.NewIntInt(2), rt.NewIntInt(3), rt.NewIntInt(4), rt.NewIntInt(5)}}
	globals["xs"] = xs
	_ = rt.Must(rt.Call(loadName("print"), xs))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Call(loadName("len"), xs))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.GetItem(xs, rt.NewIntInt(0)))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.GetItem(xs, rt.Must(rt.Neg(rt.NewIntInt(1)))))))
	total = rt.NewIntInt(0)
	globals["total"] = total
	{
		_it1 := rt.MustIter(rt.GetIter(xs))
		for {
			_v, _ok := _it1.Next()
			if !_ok {
				break
			}
			v = _v
			globals["v"] = v
			total = rt.Must(rt.Add(total, v))
			globals["total"] = total
		}
	}
	_ = rt.Must(rt.Call(loadName("print"), total))
	if err := rt.SetItem(xs, rt.NewIntInt(0), rt.NewIntInt(99)); err != nil {
		panic(err)
	}
	_ = rt.Must(rt.Call(loadName("print"), xs))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Contains(xs, rt.NewIntInt(3)))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Contains(xs, rt.NewIntInt(42)))))
}
