//go:build ignore

// Code generated by gopygo. DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	rt "github.com/tamnd/gopygo/runtime"
)

var globals = map[string]rt.Value{}

func loadName(name string) rt.Value {
	if v, ok := globals[name]; ok {
		return v
	}
	if v, ok := rt.Builtins[name]; ok {
		return v
	}
	panic(fmt.Sprintf("NameError: name %q is not defined", name))
}

func main() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, r)
			os.Exit(1)
		}
	}()
	var d rt.Value
	var k rt.Value
	d = rt.NewDictFromPairs(rt.NewStr("a"), rt.NewIntInt(1), rt.NewStr("b"), rt.NewIntInt(2))
	globals["d"] = d
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.GetItem(d, rt.NewStr("a")))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.GetItem(d, rt.NewStr("b")))))
	if err := rt.SetItem(d, rt.NewStr("c"), rt.NewIntInt(3)); err != nil {
		panic(err)
	}
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.GetItem(d, rt.NewStr("c")))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Contains(d, rt.NewStr("a")))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Contains(d, rt.NewStr("z")))))
	{
		_it1 := rt.MustIter(rt.GetIter(rt.NewTuple(rt.NewStr("a"), rt.NewStr("b"), rt.NewStr("c"))))
		for {
			_v, _ok := _it1.Next()
			if !_ok {
				break
			}
			k = _v
			globals["k"] = k
			_ = rt.Must(rt.Call(loadName("print"), k, rt.Must(rt.GetItem(d, k))))
		}
	}
}
