//go:build ignore

// Code generated by gopygo. DO NOT EDIT.

package main

import (
	"fmt"
	"strconv"
	"strings"
)

func main() {
	var ages map[string]int64 = map[string]int64{"alice": 30, "bob": 25}
	pyPrintln(ages["alice"])
	pyPrintln(ages["bob"])
	ages["carol"] = 40
	pyPrintln(int64(len(ages)))
}

func pyRepr(v any) string {
	switch x := v.(type) {
	case bool:
		if x {
			return "True"
		}
		return "False"
	case float64:
		if x == float64(int64(x)) {
			return strconv.FormatFloat(x, 'f', 1, 64)
		}
		return strconv.FormatFloat(x, 'g', -1, 64)
	case string:
		return x
	}
	return fmt.Sprint(v)
}

func pyPrintln(args ...any) {
	parts := make([]string, len(args))
	for i, a := range args {
		parts[i] = pyRepr(a)
	}
	fmt.Println(strings.Join(parts, " "))
}
