//go:build ignore

// Code generated by gopygo. DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	rt "github.com/tamnd/gopygo/runtime"
)

var globals = map[string]rt.Value{}

func loadName(name string) rt.Value {
	if v, ok := globals[name]; ok {
		return v
	}
	if v, ok := rt.Builtins[name]; ok {
		return v
	}
	panic(fmt.Sprintf("NameError: name %q is not defined", name))
}

func main() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, r)
			os.Exit(1)
		}
	}()
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Call(loadName("abs"), rt.Must(rt.Neg(rt.NewIntInt(5)))))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Call(loadName("abs"), rt.NewIntInt(3)))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Call(loadName("min"), rt.NewIntInt(3), rt.NewIntInt(1), rt.NewIntInt(2)))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Call(loadName("max"), rt.NewIntInt(3), rt.NewIntInt(1), rt.NewIntInt(2)))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Call(loadName("min"), &rt.List{V: []rt.Value{rt.NewIntInt(5), rt.NewIntInt(2), rt.NewIntInt(8), rt.NewIntInt(1), rt.NewIntInt(9)}}))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Call(loadName("max"), &rt.List{V: []rt.Value{rt.NewIntInt(5), rt.NewIntInt(2), rt.NewIntInt(8), rt.NewIntInt(1), rt.NewIntInt(9)}}))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Call(loadName("str"), rt.NewIntInt(42)))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Call(loadName("int"), rt.NewStr("123")))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Call(loadName("int"), rt.NewFloat(3.7)))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Call(loadName("bool"), rt.NewIntInt(0)))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Call(loadName("bool"), rt.NewIntInt(1)))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Call(loadName("bool"), rt.NewStr("")))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Call(loadName("bool"), rt.NewStr("x")))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Call(loadName("list"), rt.Must(rt.Call(loadName("range"), rt.NewIntInt(4)))))))
}
