//go:build ignore

// Code generated by gopygo. DO NOT EDIT.

package main

import (
	"fmt"
	"strconv"
	"strings"
)

func main() {
	pyPrintln(absInt(-7))
	pyPrintln(absInt(3))
	pyPrintln(minInt(3, 1, 4, 1, 5))
	pyPrintln(maxInt(3, 1, 4, 1, 5))
	pyPrintln(mustAtoi64("42"))
	pyPrintln(float64(3))
	pyPrintln(fmt.Sprint(100))
}

func absInt(x int64) int64 {
	if x < 0 {
		return -x
	}
	return x
}

func minInt(xs ...int64) int64 {
	m := xs[0]
	for _, v := range xs[1:] {
		if v < m {
			m = v
		}
	}
	return m
}

func maxInt(xs ...int64) int64 {
	m := xs[0]
	for _, v := range xs[1:] {
		if v > m {
			m = v
		}
	}
	return m
}

func mustAtoi64(s string) int64 {
	n, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		panic("invalid literal for int(): " + s)
	}
	return n
}

func pyRepr(v any) string {
	switch x := v.(type) {
	case bool:
		if x {
			return "True"
		}
		return "False"
	case float64:
		if x == float64(int64(x)) {
			return strconv.FormatFloat(x, 'f', 1, 64)
		}
		return strconv.FormatFloat(x, 'g', -1, 64)
	case string:
		return x
	}
	return fmt.Sprint(v)
}

func pyPrintln(args ...any) {
	parts := make([]string, len(args))
	for i, a := range args {
		parts[i] = pyRepr(a)
	}
	fmt.Println(strings.Join(parts, " "))
}
