//go:build ignore

// Code generated by gopygo. DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	rt "github.com/tamnd/gopygo/runtime"
)

var globals = map[string]rt.Value{}

func loadName(name string) rt.Value {
	if v, ok := globals[name]; ok {
		return v
	}
	if v, ok := rt.Builtins[name]; ok {
		return v
	}
	panic(fmt.Sprintf("NameError: name %q is not defined", name))
}

func main() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, r)
			os.Exit(1)
		}
	}()
	var i rt.Value
	{
		_it1 := rt.MustIter(rt.GetIter(rt.Must(rt.Call(loadName("range"), rt.NewIntInt(1), rt.NewIntInt(21)))))
		for {
			_v, _ok := _it1.Next()
			if !_ok {
				break
			}
			i = _v
			globals["i"] = i
			if rt.Truthy(rt.Boxed(rt.Equal(rt.Must(rt.Mod(i, rt.NewIntInt(15))), rt.NewIntInt(0)))) {
				_ = rt.Must(rt.Call(loadName("print"), rt.NewStr("FizzBuzz")))
			} else if rt.Truthy(rt.Boxed(rt.Equal(rt.Must(rt.Mod(i, rt.NewIntInt(3))), rt.NewIntInt(0)))) {
				_ = rt.Must(rt.Call(loadName("print"), rt.NewStr("Fizz")))
			} else if rt.Truthy(rt.Boxed(rt.Equal(rt.Must(rt.Mod(i, rt.NewIntInt(5))), rt.NewIntInt(0)))) {
				_ = rt.Must(rt.Call(loadName("print"), rt.NewStr("Buzz")))
			} else {
				_ = rt.Must(rt.Call(loadName("print"), i))
			}
		}
	}
}
