//go:build ignore

// Code generated by gopygo. DO NOT EDIT.

package main

import (
	"fmt"
	"strconv"
	"strings"
)

func main() {
	for i := int64(1); i < 16; i++ {
		if (i % 15) == 0 {
			pyPrintln("FizzBuzz")
		} else if (i % 3) == 0 {
			pyPrintln("Fizz")
		} else if (i % 5) == 0 {
			pyPrintln("Buzz")
		} else {
			pyPrintln(i)
		}
	}
}

func pyRepr(v any) string {
	switch x := v.(type) {
	case bool:
		if x {
			return "True"
		}
		return "False"
	case float64:
		if x == float64(int64(x)) {
			return strconv.FormatFloat(x, 'f', 1, 64)
		}
		return strconv.FormatFloat(x, 'g', -1, 64)
	case string:
		return x
	}
	return fmt.Sprint(v)
}

func pyPrintln(args ...any) {
	parts := make([]string, len(args))
	for i, a := range args {
		parts[i] = pyRepr(a)
	}
	fmt.Println(strings.Join(parts, " "))
}
