//go:build ignore

// Code generated by gopygo. DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	rt "github.com/tamnd/gopygo/runtime"
)

var globals = map[string]rt.Value{}

func loadName(name string) rt.Value {
	if v, ok := globals[name]; ok {
		return v
	}
	if v, ok := rt.Builtins[name]; ok {
		return v
	}
	panic(fmt.Sprintf("NameError: name %q is not defined", name))
}

var _fn_fact = &rt.Func{Name: "fact", Arity: 1, Impl: _impl_fact}

func _impl_fact(_args []rt.Value) (rt.Value, error) {
	if len(_args) != 1 {
		return nil, rt.TypeError("fact() takes 1 positional arguments but %d were given", len(_args))
	}
	n := _args[0]
	var i rt.Value
	var r rt.Value
	_ = _args
	r = rt.NewIntInt(1)
	{
		_it1 := rt.MustIter(rt.GetIter(rt.Must(rt.Call(loadName("range"), rt.NewIntInt(1), rt.Must(rt.Add(n, rt.NewIntInt(1)))))))
		for {
			_v, _ok := _it1.Next()
			if !_ok {
				break
			}
			i = _v
			r = rt.Must(rt.Mul(r, i))
		}
	}
	return r, nil
	return rt.None, nil
}

func main() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, r)
			os.Exit(1)
		}
	}()
	var fact rt.Value
	fact = _fn_fact
	globals["fact"] = fact
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Call(fact, rt.NewIntInt(20)))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Call(fact, rt.NewIntInt(50)))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Call(fact, rt.NewIntInt(100)))))
	_ = rt.Must(rt.Call(loadName("print"), rt.Must(rt.Pow(rt.NewIntInt(2), rt.NewIntInt(128)))))
}
