//go:build ignore

// Code generated by gopygo. DO NOT EDIT.

package main

import (
	"fmt"
	"strconv"
	"strings"
)

func square(x int64) int64 {
	return (x * x)
}

func sum_of_squares(n int64) int64 {
	var total int64 = 0
	for i := int64(1); i < (n + 1); i++ {
		total = (total + square(i))
	}
	return total
}

func main() {
	pyPrintln(sum_of_squares(10))
	pyPrintln(sum_of_squares(100))
}

func pyRepr(v any) string {
	switch x := v.(type) {
	case bool:
		if x {
			return "True"
		}
		return "False"
	case float64:
		if x == float64(int64(x)) {
			return strconv.FormatFloat(x, 'f', 1, 64)
		}
		return strconv.FormatFloat(x, 'g', -1, 64)
	case string:
		return x
	}
	return fmt.Sprint(v)
}

func pyPrintln(args ...any) {
	parts := make([]string, len(args))
	for i, a := range args {
		parts[i] = pyRepr(a)
	}
	fmt.Println(strings.Join(parts, " "))
}
