//go:build ignore

// Code generated by gopygo. DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	rt "github.com/tamnd/gopygo/runtime"
)

var globals = map[string]rt.Value{}

func loadName(name string) rt.Value {
	if v, ok := globals[name]; ok { return v }
	if v, ok := rt.Builtins[name]; ok { return v }
	panic(fmt.Sprintf("NameError: name %q is not defined", name))
}

func main() {
	if _, err := py_module__1(nil); err != nil {
		fmt.Fprintln(os.Stderr, err); os.Exit(1)
	}
}

// <module> from tests/fixtures/call_chain.py:1
func py_module__1(args []rt.Value) (rt.Value, error) {
	var stk [5]rt.Value
	var sp int
	_ = stk; _ = sp
	// RESUME 0
	stk[sp] = &rt.Func{Name: "a", Arity: 1, Impl: py_a__2}; sp++
	// MAKE_FUNCTION (wrapped at LOAD_CONST)
	sp--; globals["a"] = stk[sp]
	stk[sp] = &rt.Func{Name: "b", Arity: 1, Impl: py_b__3}; sp++
	// MAKE_FUNCTION (wrapped at LOAD_CONST)
	sp--; globals["b"] = stk[sp]
	stk[sp] = &rt.Func{Name: "c", Arity: 1, Impl: py_c__4}; sp++
	// MAKE_FUNCTION (wrapped at LOAD_CONST)
	sp--; globals["c"] = stk[sp]
	stk[sp] = loadName("print"); sp++
	stk[sp] = nil; sp++
	stk[sp] = loadName("c"); sp++
	stk[sp] = nil; sp++
	stk[sp] = rt.NewIntInt(5); sp++
	{
		callable := stk[sp-1-2]
		_ = stk[sp-1-1] // NULL/self
		callArgs := make([]rt.Value, 1)
		copy(callArgs, stk[sp-1:sp])
		r, err := rt.Call(callable, callArgs...)
		if err != nil { return nil, err }
		sp = sp - 1 - 2
		stk[sp] = r; sp++
	}
	{
		callable := stk[sp-1-2]
		_ = stk[sp-1-1] // NULL/self
		callArgs := make([]rt.Value, 1)
		copy(callArgs, stk[sp-1:sp])
		r, err := rt.Call(callable, callArgs...)
		if err != nil { return nil, err }
		sp = sp - 1 - 2
		stk[sp] = r; sp++
	}
	sp--
	stk[sp] = rt.None; sp++
	sp--; return stk[sp], nil
	return rt.None, nil
}

// a from tests/fixtures/call_chain.py:1
func py_a__2(args []rt.Value) (rt.Value, error) {
	var _L0 rt.Value
	_ = _L0
	for i := 0; i < len(args) && i < 1; i++ {
		switch i {
		case 0: _L0 = args[0]
		}
	}
	var stk [4]rt.Value
	var sp int
	_ = stk; _ = sp
	// RESUME 0
	stk[sp] = _L0; sp++
	stk[sp] = rt.NewIntInt(1); sp++
	{ sp--; r, err := rt.Add(stk[sp-1], stk[sp]); if err != nil { return nil, err }; stk[sp-1] = r }
	sp--; return stk[sp], nil
	return rt.None, nil
}

// b from tests/fixtures/call_chain.py:3
func py_b__3(args []rt.Value) (rt.Value, error) {
	var _L0 rt.Value
	_ = _L0
	for i := 0; i < len(args) && i < 1; i++ {
		switch i {
		case 0: _L0 = args[0]
		}
	}
	var stk [4]rt.Value
	var sp int
	_ = stk; _ = sp
	// RESUME 0
	stk[sp] = loadName("a"); sp++
	stk[sp] = nil; sp++
	stk[sp] = _L0; sp++
	{
		callable := stk[sp-1-2]
		_ = stk[sp-1-1] // NULL/self
		callArgs := make([]rt.Value, 1)
		copy(callArgs, stk[sp-1:sp])
		r, err := rt.Call(callable, callArgs...)
		if err != nil { return nil, err }
		sp = sp - 1 - 2
		stk[sp] = r; sp++
	}
	stk[sp] = rt.NewIntInt(2); sp++
	{ sp--; r, err := rt.Mul(stk[sp-1], stk[sp]); if err != nil { return nil, err }; stk[sp-1] = r }
	sp--; return stk[sp], nil
	return rt.None, nil
}

// c from tests/fixtures/call_chain.py:5
func py_c__4(args []rt.Value) (rt.Value, error) {
	var _L0 rt.Value
	_ = _L0
	for i := 0; i < len(args) && i < 1; i++ {
		switch i {
		case 0: _L0 = args[0]
		}
	}
	var stk [4]rt.Value
	var sp int
	_ = stk; _ = sp
	// RESUME 0
	stk[sp] = loadName("b"); sp++
	stk[sp] = nil; sp++
	stk[sp] = _L0; sp++
	{
		callable := stk[sp-1-2]
		_ = stk[sp-1-1] // NULL/self
		callArgs := make([]rt.Value, 1)
		copy(callArgs, stk[sp-1:sp])
		r, err := rt.Call(callable, callArgs...)
		if err != nil { return nil, err }
		sp = sp - 1 - 2
		stk[sp] = r; sp++
	}
	stk[sp] = rt.NewIntInt(3); sp++
	{ sp--; r, err := rt.Sub(stk[sp-1], stk[sp]); if err != nil { return nil, err }; stk[sp-1] = r }
	sp--; return stk[sp], nil
	return rt.None, nil
}

