//go:build ignore

// Code generated by gopygo. DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	rt "github.com/tamnd/gopygo/runtime"
)

var globals = map[string]rt.Value{}

func loadName(name string) rt.Value {
	if v, ok := globals[name]; ok { return v }
	if v, ok := rt.Builtins[name]; ok { return v }
	panic(fmt.Sprintf("NameError: name %q is not defined", name))
}

func main() {
	if _, err := py_module__1(nil); err != nil {
		fmt.Fprintln(os.Stderr, err); os.Exit(1)
	}
}

// <module> from tests/fixtures/fib_rec.py:1
func py_module__1(args []rt.Value) (rt.Value, error) {
	var stk [5]rt.Value
	var sp int
	_ = stk; _ = sp
	// RESUME 0
	stk[sp] = &rt.Func{Name: "fib", Arity: 1, Impl: py_fib__2}; sp++
	// MAKE_FUNCTION (wrapped at LOAD_CONST)
	sp--; globals["fib"] = stk[sp]
	stk[sp] = loadName("print"); sp++
	stk[sp] = nil; sp++
	stk[sp] = loadName("fib"); sp++
	stk[sp] = nil; sp++
	stk[sp] = rt.NewIntInt(20); sp++
	{
		callable := stk[sp-1-2]
		_ = stk[sp-1-1] // NULL/self
		callArgs := make([]rt.Value, 1)
		copy(callArgs, stk[sp-1:sp])
		r, err := rt.Call(callable, callArgs...)
		if err != nil { return nil, err }
		sp = sp - 1 - 2
		stk[sp] = r; sp++
	}
	{
		callable := stk[sp-1-2]
		_ = stk[sp-1-1] // NULL/self
		callArgs := make([]rt.Value, 1)
		copy(callArgs, stk[sp-1:sp])
		r, err := rt.Call(callable, callArgs...)
		if err != nil { return nil, err }
		sp = sp - 1 - 2
		stk[sp] = r; sp++
	}
	sp--
	stk[sp] = rt.None; sp++
	sp--; return stk[sp], nil
	return rt.None, nil
}

// fib from tests/fixtures/fib_rec.py:1
func py_fib__2(args []rt.Value) (rt.Value, error) {
	var _L0 rt.Value
	_ = _L0
	for i := 0; i < len(args) && i < 1; i++ {
		switch i {
		case 0: _L0 = args[0]
		}
	}
	var stk [5]rt.Value
	var sp int
	_ = stk; _ = sp
	// RESUME 0
	stk[sp] = _L0; sp++
	stk[sp] = rt.NewIntInt(2); sp++
	{ sp--; r, err := rt.Compare(0, stk[sp-1], stk[sp]); if err != nil { return nil, err }; stk[sp-1] = r }
	{ sp--; if !rt.Truthy(stk[sp]) { goto L20 } }
	// NOT_TAKEN 0
	stk[sp] = _L0; sp++
	sp--; return stk[sp], nil
L20:
	stk[sp] = loadName("fib"); sp++
	stk[sp] = nil; sp++
	stk[sp] = _L0; sp++
	stk[sp] = rt.NewIntInt(1); sp++
	{ sp--; r, err := rt.Sub(stk[sp-1], stk[sp]); if err != nil { return nil, err }; stk[sp-1] = r }
	{
		callable := stk[sp-1-2]
		_ = stk[sp-1-1] // NULL/self
		callArgs := make([]rt.Value, 1)
		copy(callArgs, stk[sp-1:sp])
		r, err := rt.Call(callable, callArgs...)
		if err != nil { return nil, err }
		sp = sp - 1 - 2
		stk[sp] = r; sp++
	}
	stk[sp] = loadName("fib"); sp++
	stk[sp] = nil; sp++
	stk[sp] = _L0; sp++
	stk[sp] = rt.NewIntInt(2); sp++
	{ sp--; r, err := rt.Sub(stk[sp-1], stk[sp]); if err != nil { return nil, err }; stk[sp-1] = r }
	{
		callable := stk[sp-1-2]
		_ = stk[sp-1-1] // NULL/self
		callArgs := make([]rt.Value, 1)
		copy(callArgs, stk[sp-1:sp])
		r, err := rt.Call(callable, callArgs...)
		if err != nil { return nil, err }
		sp = sp - 1 - 2
		stk[sp] = r; sp++
	}
	{ sp--; r, err := rt.Add(stk[sp-1], stk[sp]); if err != nil { return nil, err }; stk[sp-1] = r }
	sp--; return stk[sp], nil
	return rt.None, nil
}

