//go:build ignore

// Code generated by gopygo. DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	rt "github.com/tamnd/gopygo/runtime"
)

var globals = map[string]rt.Value{}

func loadName(name string) rt.Value {
	if v, ok := globals[name]; ok { return v }
	if v, ok := rt.Builtins[name]; ok { return v }
	panic(fmt.Sprintf("NameError: name %q is not defined", name))
}

func main() {
	if _, err := py_module__1(nil); err != nil {
		fmt.Fprintln(os.Stderr, err); os.Exit(1)
	}
}

// <module> from tests/fixtures/fib_iter.py:1
func py_module__1(args []rt.Value) (rt.Value, error) {
	var stk [4]rt.Value
	var sp int
	_ = stk; _ = sp
	// RESUME 0
	stk[sp] = rt.NewIntInt(0); sp++
	sp--; globals["a"] = stk[sp]
	stk[sp] = rt.NewIntInt(1); sp++
	sp--; globals["b"] = stk[sp]
	stk[sp] = rt.NewIntInt(0); sp++
	sp--; globals["i"] = stk[sp]
L14:
	stk[sp] = loadName("i"); sp++
	stk[sp] = rt.NewIntInt(50); sp++
	{ sp--; r, err := rt.Compare(0, stk[sp-1], stk[sp]); if err != nil { return nil, err }; stk[sp-1] = r }
	{ sp--; if !rt.Truthy(stk[sp]) { goto L74 } }
	// NOT_TAKEN 0
	stk[sp] = loadName("b"); sp++
	stk[sp] = loadName("a"); sp++
	stk[sp] = loadName("b"); sp++
	{ sp--; r, err := rt.Add(stk[sp-1], stk[sp]); if err != nil { return nil, err }; stk[sp-1] = r }
	stk[sp-1], stk[sp-2] = stk[sp-2], stk[sp-1]
	sp--; globals["a"] = stk[sp]
	sp--; globals["b"] = stk[sp]
	stk[sp] = loadName("i"); sp++
	stk[sp] = rt.NewIntInt(1); sp++
	{ sp--; r, err := rt.Add(stk[sp-1], stk[sp]); if err != nil { return nil, err }; stk[sp-1] = r }
	sp--; globals["i"] = stk[sp]
	goto L14
L74:
	stk[sp] = loadName("print"); sp++
	stk[sp] = nil; sp++
	stk[sp] = loadName("a"); sp++
	{
		callable := stk[sp-1-2]
		_ = stk[sp-1-1] // NULL/self
		callArgs := make([]rt.Value, 1)
		copy(callArgs, stk[sp-1:sp])
		r, err := rt.Call(callable, callArgs...)
		if err != nil { return nil, err }
		sp = sp - 1 - 2
		stk[sp] = r; sp++
	}
	sp--
	stk[sp] = rt.None; sp++
	sp--; return stk[sp], nil
	return rt.None, nil
}

