//go:build ignore

// Code generated by gopygo. DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	rt "github.com/tamnd/gopygo/runtime"
)

var globals = map[string]rt.Value{}

func loadName(name string) rt.Value {
	if v, ok := globals[name]; ok { return v }
	if v, ok := rt.Builtins[name]; ok { return v }
	panic(fmt.Sprintf("NameError: name %q is not defined", name))
}

func main() {
	if _, err := py_module__1(nil); err != nil {
		fmt.Fprintln(os.Stderr, err); os.Exit(1)
	}
}

// <module> from tests/fixtures/fstring_simple.py:1
func py_module__1(args []rt.Value) (rt.Value, error) {
	var stk [4]rt.Value
	var sp int
	_ = stk; _ = sp
	// RESUME 0
	stk[sp] = rt.NewIntInt(7); sp++
	sp--; globals["x"] = stk[sp]
	stk[sp] = loadName("print"); sp++
	stk[sp] = nil; sp++
	stk[sp] = rt.NewStr("x is "); sp++
	stk[sp] = loadName("x"); sp++
	stk[sp-1] = rt.Format(stk[sp-1])
	{ r := rt.ConcatStrings(stk[sp-2:sp]); sp -= 2; stk[sp] = r; sp++ }
	{
		callable := stk[sp-1-2]
		_ = stk[sp-1-1] // NULL/self
		callArgs := make([]rt.Value, 1)
		copy(callArgs, stk[sp-1:sp])
		r, err := rt.Call(callable, callArgs...)
		if err != nil { return nil, err }
		sp = sp - 1 - 2
		stk[sp] = r; sp++
	}
	sp--
	stk[sp] = rt.NewStr("world"); sp++
	sp--; globals["name"] = stk[sp]
	stk[sp] = loadName("print"); sp++
	stk[sp] = nil; sp++
	stk[sp] = rt.NewStr("hello "); sp++
	stk[sp] = loadName("name"); sp++
	stk[sp-1] = rt.Format(stk[sp-1])
	{ r := rt.ConcatStrings(stk[sp-2:sp]); sp -= 2; stk[sp] = r; sp++ }
	{
		callable := stk[sp-1-2]
		_ = stk[sp-1-1] // NULL/self
		callArgs := make([]rt.Value, 1)
		copy(callArgs, stk[sp-1:sp])
		r, err := rt.Call(callable, callArgs...)
		if err != nil { return nil, err }
		sp = sp - 1 - 2
		stk[sp] = r; sp++
	}
	sp--
	stk[sp] = rt.None; sp++
	sp--; return stk[sp], nil
	return rt.None, nil
}

